//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SurvUtilArx.rc
//
#define IDC_ADD                         3
#define IDDRAW                          3
#define IDSETLYR                        3
#define IDLYRSETTING                    3
#define IDC_DEL                         4
#define IDSETANNTAGS                    4
#define IDANNTAGSSETTING                4
#define IDC_DELALL                      5
#define IDSET_SURF_MARKER               5
#define IDSET_OUTFILE                   6
#define IDD_ABOUTBOX                    100
#define IDR_TOOLBAR_SURVUTIL            101
#define CG_IDD_PROGRESS                 103
#define CG_IDS_PROGRESS_CAPTION         104
#define IDD_LICENSE_KEY_SELECTION       104
#define IDS_ABOUTBOX                    105
#define IDD_RXD_OUT                     106
#define IDS_STRING_COMPANY              107
#define IDD_PIN_OUT                     108
#define IDD_INS_BLK_UTIL                109
#define IDD_ABOUTME                     110
#define IDS_STRING_AUTH_CODE_TAG        113
#define IDD_CONVERT_FIELD_DATA          114
#define IDS_STRING_AUTH_CODE_VAL        115
#define IDD_DIALOG_RESULTS              116
#define IDS_STRING_ACTIVATION_CODE_VAL  117
#define IDS_STRING_ACTIVATION_CODE_TAG  118
#define IDS_STRING_VERSION              119
#define IDS_STRING_THIS_ARX_NAME        120
#define IDS_STRING_THIS_ARX_REG_PATH    121
#define IDD_DIALOG_ACTIVATION           122
#define IDR_MYSELF                      123
#define IDR_CONTOUR                     124
#define IDC_BUTTON_ME                   125
#define IDD_DIALOG_JOIN_SEL_PTS         126
#define IDD_COMPILE_XLS                 127
#define IDD_PROFILE_CHG_Z               128
#define IDI_ADDTO_QUE                   129
#define IDD_XSEC_XLS                    130
#define IDR_MENU_XL_READER_DLG          130
#define IDR_MENU_POPUP                  130
#define IDI_OUTPUT_VW                   131
#define IDD_XSEC_FROM_DWG               132
#define IDD_XSEC_FROM_OFF_ELEV_DATA     133
#define IDI_LIST_VW                     134
#define IDR_TOOLBAR_SURVUTIL_NEW        136
#define IDD_RD_PROFILE_CHG_Z_FROM_XLS   137
#define IDD_DIALOG_TRAVERSE             138
#define IDD_XSEC_FROM_OFF_ELEV_DATA_EX  139
#define IDD_DIALOG_LYR_SETTING          140
#define IDD_MODIFY_SURV_TAGS_DLG        141
#define IDD_RD_PLAN_FROM_TXT_FILE       142
#define IDD_RD_PLAN_TXT_FILE_MODIFY     143
#define IDD_UTIL_DOUBLE_INPUT           144
#define IDD_INS_BLK_FROM_TXTFILE        145
#define IDD_PROFILE_SURF_PARAM          146
#define IDD_FB_SHEET_PARAM              147
#define IDD_RD_PROFILE_CHG_Z_FROM_DATAFILE 148
#define IDD_FIND_POINT_WRT_CHG          149
#define IDD_CHG_RANGE                   150
#define IDD_LICENSE_KEY_SELECTION1      151
#define IDC_CHECK_Z_FLAG_PIN            1001
#define CG_IDC_PROGDLG_PROGRESS         1003
#define IDC_EDIT_DISP_INSTALL_INFO      1003
#define IDC_CHECK                       1004
#define IDC_CHECK_SPLEVEL_FLAG          1005
#define IDC_CHECK_DRAW_GEN_PTS          1005
#define IDC_BUTTON_INP_FILE             1006
#define IDC_SEL_XLS                     1007
#define IDC_CHECK_DESC_FLAG             1008
#define IDC_CHECK_ZFLAG                 1009
#define CG_IDC_PROGDLG_STATUS           1010
#define IDC_HAS_Z_DATA                  1010
#define IDC_BUTTON_OUT_FILE             1011
#define IDC_SEL_OUT                     1013
#define IDC_EDIT_LAB_TXT_SIZE           1014
#define IDC_EDIT_NUM_TXT_SIZE           1015
#define IDC_EDIT_ROW_HT                 1016
#define IDC_EDIT_BLK_SCALE              1017
#define IDC_EDIT_CS_LABEL_SIZE          1017
#define IDC_EDIT_CS_LABEL_TXT           1017
#define IDC_EDIT_TXT_ANGLE              1017
#define IDC_EDIT_RESULT                 1018
#define IDC_EDIT_ORDINATE_INTERVAL      1018
#define IDC_EDIT_TXT_MARGIN             1018
#define IDC_EDIT_LYR                    1019
#define IDC_EDIT_EXAG_HORZ              1020
#define IDC_EDIT_TXT_SIZE               1021
#define IDC_EDIT_EXAG_VERT              1023
#define IDC_CHECK_Z_FLAG_RXD            1024
#define IDC_EDIT_DATUM                  1025
#define IDC_EDIT_ROW                    1026
#define IDC_EDIT_ORD_INTERVAL           1026
#define IDC_EDIT_SPLEVEL_LYR            1027
#define IDC_EDIT_BLK_ROT_ANGLE          1028
#define IDC_EDIT3                       1028
#define IDC_EDIT_LYR_RXD                1029
#define IDC_EDIT_TXT_ROT_ANGLE          1029
#define IDC_EDIT_COL                    1030
#define IDC_EDIT_BLK_SCALE_X            1031
#define IDC_EDIT_LYR_PID                1032
#define IDC_EDIT_MIN_SPACE              1032
#define IDC_EDIT_START_CHG              1033
#define IDC_EDIT_BLK_SCALE_Y            1034
#define IDC_EDIT                        1034
#define IDC_CHECK_Z_FLAG_PID            1035
#define IDC_EDIT_SHEET_WIDTH            1036
#define IDC_EDIT_BLK_SCALE_Z            1037
#define IDC_EDIT_SHEET_HEIGHT           1038
#define IDC_STATIC_MSG                  1038
#define IDC_EDIT_INP_FILE               1039
#define IDC_EDIT_NAMEPLATE_WIDTH        1040
#define IDC_EDIT_OUT_FILE               1041
#define IDC_CHECK_SHOW_PTNO             1042
#define IDC_EDIT_NAMEPLATE_HEIGHT       1043
#define IDC_EDIT_END_CHG                1044
#define IDC_LIST_SRC                    1045
#define IDC_LIST_DEST                   1046
#define IDC_EDIT1                       1047
#define IDC_EDIT_DET_SRC                1048
#define IDC_EDIT_TAB_TXT                1048
#define IDC_EDIT_PT_TXT_ANG             1049
#define IDC_EDIT_TAB_MARGIN             1049
#define IDC_EDIT2                       1050
#define IDC_EDIT_DET_DEST               1051
#define IDC_COMBO_BLK_NAME              1052
#define IDC_LIST1                       1053
#define IDC_CONVERT                     1054
#define IDC_BUTTON_ADDTO_QUE            1055
#define IDC_BUTTON_RESET                1056
#define IDC_COMBO_BLOCK                 1057
#define IDC_LIST_LEV_RANGE              1058
#define IDC_BUTTON_VIEW                 1059
#define IDC_EDIT_DATUM_START            1060
#define IDC_STATIC_VIEW                 1061
#define IDC_EDIT_MIN_ORD_HT             1061
#define IDC_EDIT_DATUM_END              1062
#define IDC_PROGRESS1                   1063
#define IDC_EDIT_DATUM_DENOMINATOR      1063
#define IDC_BUTTON_ADD_RANGE            1064
#define IDC_BUTTON_FILE                 1064
#define IDC_STATIC_PROGRESS             1065
#define IDC_EDIT_OUTPUT                 1066
#define IDC_EDIT_DATUM_ELEV             1067
#define IDC_EDIT_ELEV_TAG               1068
#define IDC_EDIT_CUM_DIST_TAG           1069
#define IDC_OPEN_CSD                    1070
#define IDC_STATIC_LICENSE              1070
#define IDC_EDIT_NORTHING_TAG           1071
#define IDC_OPEN_CSD_DSGN               1071
#define IDC_EDIT_FILENAME               1072
#define IDC_EDIT_LYR_TOP_SURFACE        1073
#define IDC_OPEN_LOG                    1073
#define IDC_EDIT_EASTING_TAG            1074
#define IDC_EDIT_FILENAME_DSGN          1074
#define IDC_EDIT_DATUM_TAG              1075
#define IDC_EDIT_FILENAME_LOG           1075
#define IDC_EDIT_CS_LABEL_TAG           1076
#define IDC_EDIT_LYR_ORDINATE           1077
#define IDC_COMBO_SHEET                 1078
#define IDC_EDIT_OFFSET_TAG             1079
#define IDC_EDIT_LYR_ANNOTATION         1080
#define IDC_EDIT_LYR_AXIS               1081
#define IDC_EDIT_DIST_TAG               1082
#define IDC_BUTTON_DEL_RANGE            1083
#define IDC_EDIT_FILE_IN                1085
#define IDC_EDIT_FILE_OUT               1086
#define IDUPDATE                        1089
#define IDC_STATIC_LABEL                1090
#define IDC_BUTTON_LYR                  1092
#define IDC_BUTTON_ANN_TAGS             1093
#define IDC_COMBO1                      1095
#define IDC_OPEN_STN_DATA               1096
#define IDC_EDIT_FILENAME_STN           1097
#define IDC_OPEN_PID                    1098
#define IDC_EDIT_FILENAME_PID           1099
#define IDC_OPEN_OUT_FILE               1100
#define IDC_EDIT_FILENAME_OUT           1101
#define IDC_EDIT_VAL                    1102
#define IDC_STATIC_PROMPT               1103
#define IDC_OPEN_FILE                   1104
#define IDC_OPEN_DAT_FILE               1105
#define IDC_EDIT_STN_TXT                1107
#define IDC_EDIT_1                      1108
#define IDC_EDIT_2                      1109
#define IDC_EDIT_CH                     1110
#define IDC_STATIC_LICENSE_TO           1111
#define IDC_EDIT_FILENAME_CSD           1112
#define IDC_OPEN_CSD_FILE               1113
#define IDC_OPEN_PID_FILE               1114
#define IDC_COMBO_DRAW_MINMAX_ELEV_PATH 1116
#define IDC_STATIC_ORD_INTERVAL         1117
#define IDC_STATIC_X                    1118
#define IDC_CHECK_AUTO_DATUM            1119
#define IDC_CHECK_NE_ANN_SECTION        1120
#define IDC_BUTTON_LICENSE_RESET        1121
#define ID_SURVEY_SETDATA               2003
#define ID_SURVEY_DRAW_MDF_POINTS       2004
#define ID_SURVEY_DRAW_PROFILE          2005
#define ID_SURVEY_DRAW_PLAN             2006
#define ID_SURVEY_SURVEYEDPOINTS_JOINPOINTS 32773
#define ID_JOIN_SURVEYED_POINTS         32773
#define ID_SURVEY_SURVEYEDPOINTS_INS_BLOCKS 32774
#define ID_SURVEY_XPORT_SPTS            32776
#define ID_SURVEY_CONVERT_RAWSDATA      32777
#define ID_SURVEY_SEL_AND_JPOINTS       32779
#define ID_SURVEY_EDIT_PROFILE_ANN_TXT  32780
#define IDM_COMPILE_XLS                 32782
#define ID_SURVEY_DRAW_XSEC             32783
#define IDM_COMPILE_THIS                32784
#define ID_SURVEY_EDIT_XSEC             32785
#define ID_ROAD_PROFILE                 32786
#define ID_ROAD_PROFILE_DRAW            32787
#define ID_PROCCESS_FIELDBOOK           32788
#define ID_DRAW_FIELDBOOK_OBJECTS       32789
#define ID_DRAW_FIELDBOOK_XLS           32790
#define ID_BUTTON_OPENXLS               40001
#define ID_BUTTON_BATCHCOMPILE          40003
#define ID_BUTTON_CSEXN                 40004
#define ID_BUTTON_CSEXN_EDIT            40005
#define ID_BUTTON_PROFILE               40006
#define ID_BUTTON_PROFILE_EDIT          40007
#define ID_BUTTON_ROAD_PLAN             40008
#define ID_BUTTON_CONVERT_FIELD_DATA    40009
#define ID_BUTTON_COMPILE_THIS          40010
#define ID_BUTTON_DRAW_SEL_PTS          40011
#define ID_BUTTON_JOIN_POINTS           40013
#define ID_BUTTON_SEL_N_JOIN_PTS        40014
#define ID_BUTTON_RD_PROFILE            40015
#define ID_BUTTON_RD_PROFILE_EDIT       40016
#define ID_BUTTON_RD_PROFILE_OPEN       40017
#define ID_BUTTON_INS_BLKS              40018
#define ID_BUTTON_QUICK_PFL             40019
#define ID_BUTTON_QUICK_PFL_LINES       40020
#define ID_BUTTON_QUICK_PFL_PTS         40021
#define ID_BUTTON_EXPORT_POINTS         40023
#define ID_ABOUT                        40024
#define ID_ADJUST_TRAVERSE              40025
#define ID_BUTTON_RD_SURVEY             40026
#define ID_BUTTON_RD_PROFILE_MENU       40028
#define ID_BUTTON_FIELDBOOK_MENU        40029
#define ID_BUTTON40030                  40030
#define ID_BUTTON_UTIL                  40031
#define ID_BUTTON_QUICK_XSEC            40033
#define ID_BUTTON_LINE_2_PLINE          40034
#define ID_BUTTON_XSEC_FROM_CSD         40035
#define ID_BUTTON_XSEC_FROM_CSDEX       40036
#define ID_BUTTON_EDIT_PFL_AND_CS_ANN   40037
#define ID_BUTTON_INS_BLKS_FROM_FILE    40038
#define IDC_RD_PLAN_NEZ_TXTFILE         40039
#define IDC_RD_PLAN_OFFZ_TXTFILE        40040
#define IDC_RD_PLAN_NEZ_TXTFILE_MODIFY  40041
#define IDC_RD_PLAN_OFFZ_TXTFILE_MODIFY 40042
#define ID_UTILITY_MODIFY_ZVALUE        40043
#define ID_UTILITY_SETZ_VALUE           40044
#define ID_UTILITY_MODIFYTEXTSIZE       40045
#define ID_BUTTON_PFL_OFFZ_FROM_DATAFILE 40047
#define ID_ADJUST_TRAVERSE_OPEN         40048
#define IDC_RD_PLAN_OFFZ_TXTFILE_EX     40049
#define ID_BUTTON_QUICK_PFL_PTS_X       40051
#define ID_BUTTON_QUICK_PFL_LINES_X     40052
#define ID_BUTTON_QUICK_XSEC_EX         40053
#define ID_QPROFILE_PICKNANNOTATE       40054
#define IDS_CLIENT_NAME                 40054
#define IDS_CLIENT_ADDRESS              40055
#define ID_BUTTON_PFL_OFFZ_FROM_DATAFILE_EX 40056
#define ID_BUTTON_LINE_2_PLINE_EX       40057
#define ID_SURVEY_XPORT_SPTS_EX         40058
#define ID_UTILITY_zz                   40059
#define ID_UTILITY_ALIGN_POINTS_ON_SURVEYED_PATH 40060

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         40061
#define _APS_NEXT_CONTROL_VALUE         1122
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
